name: 'Getting WARP+ Traffic'

on:
  workflow_dispatch:
  schedule:
    - cron: '33 8 * * *'

jobs:
  auto_getting_traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Set TERM environment variable
        run: export TERM=xterm
        
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Checking
        uses: actions/checkout@v3

      - name: Setting Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Getting WARP+ Traffic
        env:
          DEVICEID: ${{ secrets.DEVICEID }}      
        run: python warp.py
